def generate_report(name, job_role, resume_score, ats_score, job_match, skills, missing_skills, section_feedback):
    report = []

    report.append("AI CAREER COMPANION – RESUME ANALYSIS REPORT")
    report.append("=" * 50)

    report.append(f"Candidate Name: {name}")
    report.append(f"Target Job Role: {job_role}")

    report.append("\nSCORES")
    report.append(f"Resume Score: {resume_score}/100")
    report.append(f"ATS Score: {ats_score}%")
    report.append(f"Job Match: {job_match}%")

    report.append("\nSKILLS FOUND")
    report.append(", ".join(skills) if skills else "No skills detected")

    report.append("\nMISSING SKILLS")
    report.append(", ".join(missing_skills) if missing_skills else "None")

    report.append("\nSECTION FEEDBACK")
    for fb in section_feedback:
        report.append(f"- {fb}")

    report.append("\nAI SUGGESTIONS")
    if missing_skills:
        report.append("• Add missing technical skills")
    if resume_score < 70:
        report.append("• Improve formatting and clarity")
    if ats_score < 70:
        report.append("• Use more job-specific keywords")

    report.append("\nGenerated by AI Career Companion")

    return "\n".join(report)
